name: sachinpp
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: lucid diaries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161824'
    - '#6a5c52'
    - '#bf9891'
    - '#b42828'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.10789712378755212
purpose: []
