name: sachinpp
favicon: null
layout_spectrum: 0.18540323060005903
typography_spectrum: 0.724878937471658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5788023448549211
  lightness: 0.5484886218328029
  saturation: 0.48476892709732056
  rhythmicContrast: 0.10789712378755212
purpose: []
